-- ============================================================================
-- 0003_questions_seed.sql  —  GENERATED by scripts/build-seed.mjs. Do not edit.
-- Source content: supabase/content/questions/*.json
-- Questions are seeded with is_active = false. Flip to true after QA:
--   update questions set is_active = true where source = 'original';
-- ============================================================================

do $seed$
declare
  v_level bigint;
  v_q     bigint;
begin
  select l.id into v_level
  from levels l
  join units u on u.id = l.unit_id
  where u.track = 'psychometric'
    and u.name  = 'כמותי – אלגברה'
    and l.position = 1;

  if v_level is null then
    raise exception 'Seed: no level for track=% unit=% position=%',
      'psychometric', 'כמותי – אלגברה', 1;
  end if;

  insert into questions (track, level_id, type, difficulty, position, body, image_url, explanation, source, is_active)
  values ('psychometric', v_level, 'multiple_choice', 2, 0, 'אם 3x + 4 = 19, מה ערכו של x?', null, 'מחסירים 4 משני האגפים: 3x = 15. מחלקים ב-3: x = 5.', 'original', false)
  returning id into v_q;

  insert into answer_options (question_id, label, body, is_correct, position) values
    (v_q, '1', '3', false, 0),
    (v_q, '2', '5', true, 1),
    (v_q, '3', '7', false, 2),
    (v_q, '4', '15', false, 3);
end
$seed$;
